### ISSUE TITLE
Lootbag issue 1.0.20

### ISSUE THREAD

**Issue by Moustik2002** [Sunekaer/stoneBlock#338]
Hi, I like very much your modpack, but there is something crashing 

Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at mal.lootbags.LootbagsUtil.generateStacks(LootbagsUtil.java:238)
	at mal.lootbags.Bag.getRandomItem(Bag.java:171)
	at mal.lootbags.item.LootbagItem.getLootItem(LootbagItem.java:230)
	at mal.lootbags.item.LootbagItem.getLootItem(LootbagItem.java:211)
	at mal.lootbags.item.LootbagItem.generateInventory(LootbagItem.java:191)
	at mal.lootbags.tileentity.TileEntityOpener.func_73660_a(TileEntityOpener.java:72)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	... 4 more

Full crash report here : https://pastebin.com/zBwVWn5w

**Comment by Sunekaer** [comment]
#320 duplicate
