### ISSUE TITLE
game crashes when starting with twitch

### ISSUE THREAD

**Issue by wyrdlg** [Sunekaer/stoneBlock#393]
Hi folks. Any ideas?
MC Launcher 1.6.91
Java 8 181
Ver 1.0.22r1

--- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.41.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.1.2.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  SBUTransformer (StoneBlockUtilities-2.0.11.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b161.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.3.0.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.1-16.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/17/18 7:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CraftPresence (craftpresence)
Caused by: java.lang.UnsatisfiedLinkError: /Documents/Curse/Minecraft/Instances/StoneBlock/craftpresence/libdiscord-rpc.dylib: dlopen(/Documents/Curse/Minecraft/Instances/StoneBlock/craftpresence/libdiscord-rpc.dylib, 1): no suitable image found.  Did find:
	/Documents/Curse/Minecraft/Instances/StoneBlock/craftpresence/libdiscord-rpc.dylib: code signature invalid for '/Documents/Curse/Minecraft/Instances/StoneBlock/craftpresence/libdiscord-rpc.dylib'

	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.gitlab.cdagaming.craftpresence.Constants.loadDLL(Constants.java:149)
	at com.gitlab.cdagaming.craftpresence.CraftPresence.init(CraftPresence.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by knoxhack** [comment]
corrupted download, try a fresh install

**Comment by Sunekaer** [comment]
This Issue is due to an Invalid DiscordDLL, It should work after removing the craftpresence folder found in .minecraft or your packs main folder, then Starting the Pack for CraftPresence to regenerate the DLLs

**Comment by wyrdlg** [comment]
Well - you Stone - Rock. That was it. Removed the whole thing in the end. Thanks!
To be honest to myself - I should have looked properly at the error...
Case closed.
