### ISSUE TITLE
Crashing mc

### ISSUE THREAD

**Issue by WujcioKarol** [Sunekaer/stoneBlock#508]
## Bug Report
minecraft crashing

## How its work
1. Launch minecraft feom twitch app
2. Click play
3. Crash

## Logs

* Client/Server Log:
* Crash Log:[09:12:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:12:53] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:12:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[09:12:53] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
[09:12:53] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_191, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_191
[09:12:54] [main/INFO] [FML]: Searching C:\Users\Karol\Documents\Curse\Minecraft\Instances\StoneBlock (1)\mods for mods
[09:12:54] [main/INFO] [FML]: Searching C:\Users\Karol\Documents\Curse\Minecraft\Instances\StoneBlock (1)\mods\1.12.2 for mods
[09:12:54] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-2.0.0.0.b161.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:12:54] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:12:54] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[09:12:54] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[09:12:54] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in comforts-1.12.2-1.3.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:12:54] [main/WARN] [FML]: The coremod c4.comforts.asm.ComfortsCoreLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:12:54] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.2.20.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:12:54] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:12:54] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[09:12:54] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in cxlibrary-1.12.1-1.6.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:12:54] [main/WARN] [FML]: The coremod cubex2.cxlibrary.CoreModLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:12:54] [main/WARN] [FML]: The coremod CXLibraryCore (cubex2.cxlibrary.CoreModLoader) is not signed!
[09:12:54] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in EnderCore-1.12.2-0.5.41.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:12:54] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in EnderCore-1.12.2-0.5.43.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:12:54] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\Karol\Documents\Curse\Minecraft\Instances\StoneBlock (1) for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:139) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalStateException: EnderCorePlugin was instantiated twice?
	at com.enderio.core.common.transform.EnderCorePlugin.<init>(EnderCorePlugin.java:58) ~[EnderCore-1.12.2-0.5.41.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_191]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_191]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:593) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:450) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:264) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2768.jar:?]
	... 5 more
Exception in thread "main" [09:12:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:12:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[09:12:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[09:12:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[09:12:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[09:12:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[09:12:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

## Client Information

* Modpack Version: 1.0.26
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by P4t0r1kku** [comment]
Java is Up-to-date? I'm now at Version 8 Build 191

**Comment by WujcioKarol** [comment]
me too I have java 8 update 191 64-bit

**Comment by P4t0r1kku** [comment]
hmm.. i see, you play on good old Win 7. i remember back in that time had sometimes trouble with 64 Bit stuff 🙄

**Comment by nzminecraftDOTcom** [comment]
Can you post the full crash log to pastebin, it's missing half the information such as the operating system, memory info, java versions, build numbers etc.

**Comment by WujcioKarol** [comment]
crash : https://pastebin.com/xuHHACVi
i only have this https://imgur.com/a/UZ0DfaE

**Comment by nzminecraftDOTcom** [comment]
That isn't from the minecraft launcher window is it? IF so, that's not the full crash report.

In your documents folder locate the curse folder, then the Minecraft folder and then the instances folder, then the stoneblock folder, then look for a folder named crash reports
Post the latest created one since you last started your game and it crashed.

**Comment by WujcioKarol** [comment]
I don't have any of that

**Comment by DV8ZXPru** [comment]
TwitchApp incorrectly updated the build without deleting outdated mods. Hence you need to remove outdated mods in folder mods.

**Comment by WujcioKarol** [comment]
Thank you guys I need to reinstal pack <3
