### ISSUE TITLE
LAN crash when connecting

### ISSUE THREAD

**Issue by colocmaram** [Sunekaer/stoneBlock#585]
Every time I try to play LAN with a friend, everything seems to work until the moment the person joining me can see their HUD. At that point, my game crashes with the following error:
```
java.lang.NullPointerException: Unexpected error
	at java.lang.String.replace(Unknown Source)
	at com.gitlab.cdagaming.craftpresence.handler.server.ServerHandler.updateServerPresence(ServerHandler.java:242)
	at com.gitlab.cdagaming.craftpresence.handler.server.ServerHandler.updateServerData(ServerHandler.java:125)
	at com.gitlab.cdagaming.craftpresence.handler.server.ServerHandler.onTick(ServerHandler.java:66)
	at com.gitlab.cdagaming.craftpresence.handler.CommandHandler.reloadData(CommandHandler.java:30)
	at com.gitlab.cdagaming.craftpresence.CraftPresence.onTick(CraftPresence.java:111)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1446_CraftPresence_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1707)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
This might just be me, but here's the steps:
1. Create world
2. open to LAN
3. Have a friend join
4. YOU crash but they just disconnect

**Comment by Sunekaer** [comment]
Use the template when making a issue

**Comment by CDAGaming** [comment]
Duplicate of #591
