### ISSUE TITLE
Stoneblock crashing instantly

### ISSUE THREAD

**Issue by Dustin2004** [Sunekaer/stoneBlock#660]
## Bug Report
 After downloading Stoneblock I start the game and after that it crashes instantly

## Steps to Reproduce (for bugs)

1. /
2./

## Logs

* Client/Server Log: The game dont start
* Crash Log: [09:56:24] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:56:24] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:56:24] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[09:56:24] [main/INFO]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
[09:56:24] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 7:amd64:6.1, installed at C:\Users\Dustin\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_51
[09:56:25] [main/INFO]: Searching C:\Users\Dustin\Documents\Curse\Minecraft\Instances\StoneBlock\mods for mods
[09:56:25] [main/INFO]: Searching C:\Users\Dustin\Documents\Curse\Minecraft\Instances\StoneBlock\mods\1.12.2 for mods
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-2.0.0.0.b161.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[09:56:25] [main/INFO]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in comforts-1.12.2-1.3.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: The coremod c4.comforts.asm.ComfortsCoreLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.2.20.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in cxlibrary-1.12.1-1.6.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: The coremod cubex2.cxlibrary.CoreModLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/WARN]: The coremod CXLibraryCore (cubex2.cxlibrary.CoreModLoader) is not signed!
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in EnderCore-1.12.2-0.5.43.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.3-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[09:56:25] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from JustEnoughIDs-1.0.1-16.jar
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in RandomThings-MC1.12.2-4.2.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:56:25] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/WARN]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[09:56:25] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:56:25] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[09:56:25] [main/INFO]: Loading tweak class name codechicken.asm.internal.Tweaker
[09:56:25] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[09:56:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.8 Source=file:/C:/Users/Dustin/Documents/Curse/Minecraft/Instances/StoneBlock/mods/JustEnoughIDs-1.0.1-16.jar Service=LaunchWrapper Env=CLIENT
[09:56:25] [main/DEBUG]: Instantiating coremod class JEIDLoadingPlugin
[09:56:25] [main/DEBUG]: The coremod org.dimdev.jeid.JEIDLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[09:56:25] [main/WARN]: The coremod JEIDLoadingPlugin (org.dimdev.jeid.JEIDLoadingPlugin) is not signed!
[09:56:25] [main/INFO]: Compatibility level set to JAVA_8
[09:56:25] [main/DEBUG]: Enqueued coremod JEIDLoadingPlugin
[09:56:25] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:56:25] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:56:25] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:56:25] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:56:25] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[09:56:25] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[09:56:25] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[09:56:26] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[09:56:26] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[09:56:26] [main/DEBUG]: Injection complete
[09:56:26] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[09:56:26] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[09:56:27] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[09:56:27] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:168) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:113) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:76) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) ~[forge-1.12.2-14.23.5.2768.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:163) ~[forge-1.12.2-14.23.5.2768.jar:?]
	... 2 more
[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## Client Information

* Modpack Version: Stoneblock-1.0.30.zip
* Server/LAN/Single Player: Cant start the game
* Optifine Installed: no 
* Shaders Enabled:no

**Comment by nzminecraftDOTcom** [comment]
Looks like it's having issues with access to some files, did you make sure you ran twitch as administrator like it suggests? Chances are it can't read/write some files it needs in order to start the game, as shown here in your crash log: 

[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.SecurityManager.checkExit(SecurityManager.java:761)

**Comment by 0-x-2-2** [comment]
> This does not look like a memory issue, it looks like it's having issues with access to some files. Do you run twitch as an administrator like it suggests? Chances are it can't read/write some files it needs in order to start the game, as shown here in your crash log:
> 
> [09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
> [09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
> [09:56:27] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.SecurityManager.checkExit(SecurityManager.java:761)

That's is unrelated to the issue and it is just forge's [SecurityManager](https://github.com/MinecraftForge/MinecraftForge/blob/5771c8ffea9a4b31043358a26ec456218a724ac0/src/main/java/net/minecraftforge/fml/relauncher/FMLSecurityManager.java#L49) throwing a exception so you can see what called "java.lang.System.exit".

The issue looks like the minecraft jar is corrupted or something did something really dumb 

> [09:56:27] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.

**Comment by Peliex** [comment]
I seem to be having an almost identical issue, right down to where the program is crashing at startup.  I haven't been able to find a solution yet, but I'm wondering if this version of Minecraft Forge is causing the issue.

**Comment by Peliex** [comment]
Found a solution!  By reverting your Forge version to 14.23.5.2772, Minecraft is once again up and running!  So in the meantime, use this version and see if that fixes your issue.  @Dustin2004
