### ISSUE TITLE
StoneBlock 1.0.32 Server Crash

### ISSUE THREAD

**Issue by ogulcanocakli** [Sunekaer/stoneBlock#773]
Hello my friend. I installed the server files as you said. But when I run, I get an error. I'm sending you an error report. Please help me.

 

---- Minecraft Crash Report ----

WARNING: coremods are present:
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.3.1.jar)
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
LoadingPlugin (RandomThings-MC1.12.2-4.2.4.jar)
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b162.jar)
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
ForgelinPlugin (Forgelin-1.8.0.jar)
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
JEIDLoadingPlugin (JustEnoughIDs-1.0.1-16.jar)
llibrary (llibrary-core-1.0.8-1.12.2.jar)
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 06.01.2019 00:00
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)
Caused by: java.lang.ExceptionInInitializerError
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at com.brandon3055.brandonscore.registry.ModFeatureParser.parseASMData(ModFeatureParser.java:76)
at com.brandon3055.brandonscore.BrandonsCore.preInit(BrandonsCore.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Block: class com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal has property: type with invalidly named value: crystal_ıo
at net.minecraft.block.state.BlockStateContainer.func_185919_a(BlockStateContainer.java:117)
at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:77)
at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:62)
at com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal.func_180661_e(EnergyCrystal.java:93)
at net.minecraft.block.Block.<init>(Block.java:234)
at net.minecraft.block.Block.<init>(Block.java:243)
at com.brandon3055.brandonscore.blocks.BlockBCore.<init>(BlockBCore.java:55)
at com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal.<init>(EnergyCrystal.java:58)
at com.brandon3055.draconicevolution.DEFeatures.<clinit>(DEFeatures.java:133)
... 39 more

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_191, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 310805624 bytes (296 MB) / 1207959552 bytes (1152 MB) up to 4294967296 bytes (4096 MB)
JVM Flags: 7 total; -Xmx4096M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2768 222 mods loaded, 222 mods active

**Comment by Gunner76th** [comment]
You will need to post this crash to Brandn3055 for Draconic Evolution as well as the crash is due to his mod primarily. I would also suggest increasing your RAM amount to 6G instead of the 4G you currently have it set to. This will help to prevent future issues.
