### ISSUE TITLE
Server doesn't launch on Windows Java 10?

### ISSUE THREAD

**Issue by Ordinaryperson2** [Sunekaer/stoneBlock#780]
Firstly: No logs attached because the server never starts, there are no logs, there is still information.

## Bug Report

When I run LaunchServer.bat there is an error immediately, without even creating a window.
If I open the cmd beforehand so it stays open I get this response:

Starting Stoneblock Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

I assume this is because I have Java 10 installed instead of Java 8, but just posting this here to be sure/have a record.

## Steps to Reproduce (for bugs)

1. Install server
2. Run server

## Client Information

* Java Version: 10.0.2+13 amd64
* Modpack Version: 1.0.33
* Server/LAN/Single Player: Server only
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Sunekaer** [comment]
minecraft is java 8, i dont know if modded minecraft is compatible with 10

**Comment by Ordinaryperson2** [comment]
I know vanilla MC is compatible because that's what i use it on. I think vanilla + optifine has a launcher issue which someone said they could work around, idk how.
It's possible forge is Java 8 only though, just wanted to check + make the error searchable.

**Comment by Espergium** [comment]
Forge is java 8. Any higher and it literally can't run.
