### ISSUE TITLE
Just a crush report that make my save broken

### ISSUE THREAD

**Issue by prototype-saber** [Sunekaer/stoneBlock#87]
## Bug Report
do nothing then crush

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:
`Time: 8/30/18 10:19 PM
Description: Tesselating block model

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=north, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:fence, properties=[east, north, south, west]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at team.chisel.ctm.client.state.CTMExtendedState.func_177229_b(CTMExtendedState.java:108)
	at net.minecraft.client.renderer.block.model.multipart.ConditionPropertyValue$2.apply(SourceFile:71)
	at net.minecraft.client.renderer.block.model.multipart.ConditionPropertyValue$2.apply(SourceFile:68)
	at pl.asie.foamfix.client.FoamyMultipartBakedModel.func_188616_a(FoamyMultipartBakedModel.java:77)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:69)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:976)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1316)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
## Client Information

* Modpack Version:1.0.14
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Sunekaer** [comment]
make a new issue and use gist.github.com or pastebin.com
